### ISSUE TITLE
Bookmarklet :: Doesn't load for Facebook images

### ISSUE THREAD

**Issue by jshapins** [Zeega/Zeega#1401]
Refused to load the script 'https://alpha.zeega.org/js/widget/zeega.bookmarklet.js?50699' because it violates the following Content Security Policy directive: "script-src https://_.facebook.com http://_.facebook.com https://_.fbcdn.net http://_.fbcdn.net _.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:_ _.spotilocal.com:_ chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl 'unsafe-inline' 'unsafe-eval' https://_.akamaihd.net http://_.akamaihd.net".

**Comment by lfbrandao** [comment]
This is due to recent Facebook changes. Working on the media library issues, will work on this later. For my ref:
http://www.html5rocks.com/en/tutorials/security/content-security-policy/
http://brianmayer.com/2012/12/defeating-chromes-content-security-policy-header-via-a-chrome-extension/

**Comment by lfbrandao** [comment]
Hey @jshapins @jamesburns  - this is a Chrome / Safari issue only, apparently due to this webkit bug:
https://bugs.webkit.org/show_bug.cgi?id=104480

The bug has been fixed on webkit, but it's still being reviewed. Apparently this is breaking a lot of Facebook extensions, so it shouldn't take long before they make the bug fix live. There are some workarounds for Chrome Extensions, but I couldn't find a way of fixing this for the bookmarklet. 

What do you think about waiting till this is fixed in Chrome / Safari?

**Comment by jshapins** [comment]
I think makes total sense to wait. Low priority.

**Comment by lfbrandao** [comment]
Works fine for me after today's Chrome update (version 24.0.1312.52)
