### ISSUE TITLE
JDA: Layers do not appear to be working with recent map updates

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#485]

**Comment by jshapins** [comment]
I noticed this, too. And it's a major issue, I'd say relative to other issues I've seen.

**Comment by kanarinka** [comment]
fd6063941be79e0851ae202697e514ba74e92a2agit

fixed now

**Comment by kanarinka** [comment]
So - to fix this I uncommented some code in jda.js that was loading the layers. This made things work but now the map seems super slow to load (not the layers & base map but the black data points take forever to show up). So this still might be an issue. Who commented out the previous code? Was that because of the speed issue?

**Comment by kanarinka** [comment]
Never mind! Sorry to spam - it is slow whether that code is commented or not so the issues are unrelated. Closing this issues and layers are working.
