### ISSUE TITLE
Working message on Bookmarklet

### ISSUE THREAD

**Issue by LindseyWagner** [Zeega/Zeega#530]
Can there be a working icon of sorts where the add button was while it's working or move the message that it may take some time there. 

"Adding media to Zeega.
This might take a while if you are importing several items. You can close the Zeega bookmarklet and continue to browse the web while the items are being imported."

and even though you can close and browse the web, it doesn't seem like you can keeping adding to zeega (bookmarklet opens up empty when it's working). Is there a way to do like a queue so the user could be adding to the line? or should we open it back up with the "still working message"

**Comment by lfbrandao** [comment]
A queue sounds good to me - large sets take a while to import and eventually timeout.

The bookmarklet should display a progress message ("10 of 100 items added to Zeega", "11 of 100 items added to Zeega", etc). If you close and open the bookmarklet while items are being added, you should be able to add more items to the queue and get an update of the queue status. This will take a while to implement and it's related to the problem of adding feeds - I think it makes sense to think about this while implementing the dynamic feeds since both problems can probably be solved together

For now I will create a limit on the number of items that can be added. Do you want to change the message above with something better?

**Comment by LindseyWagner** [comment]
What will you limit it to? Can we detect the number within a set to let a user know it's too big?

**Comment by lfbrandao** [comment]
100 items for now; the number of tags imported will also be limited to 5 per item. We should write that on the bookmarklet (and maybe on the FAQ).
